services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &        
        ollama pull llama3
        tail -f /dev/null
    restart: always



volumes:
  pgdata:
  ollama_data:
